---
- name: '安装系统安装包[libselinux-python]'
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python

- include_tasks: systemd.yml
- include_tasks: common.yml
- include_tasks: tarball.yml
- include_tasks: upstart.yml
