---
- name: Open FireWall For Port of Intranet service port
  lineinfile:
   dest=/etc/sysconfig/SuSEfirewall2 backup=no state=present
   regexp='FW_SERVICES_EXT_TCP="{{ item }}"'
   insertafter='FW_SERVICES_EXT_TCP=""'
   line='FW_SERVICES_EXT_TCP="{{ item }}"'
  register: changed
  with_items:
    - "{{ firewall_ports }}"

- name: Open FireWall
  service: name=SuSEfirewall2 state=restarted
  when: (changed|changed) and (open_firewall)
  ignore_errors: true
  

