- name: '创建SSH密钥'
  shell: 'ssh-keygen -t rsa -b 2048 -P ” -f ~/.ssh/id_rsa'
- name: '批量主机密钥分发'
  authorized_key: user=root
                  key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
                  state=present
