# [optional] to synchronize system time of nodes with 'chrony'
---
- hosts: all
  become: yes
  become_user: root
  become_method: su
  gather_facts: no 
  - name: '主机密钥分发'
    authorized_key: user=root
                    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
                    state=present 
