---
- hosts: aliyun
  vars :
    FILE_PATH: /opt/files
    JDK_VERSION: jdk-8u112-linux-x64
  tasks:
    - name: '复制jdk到远程机'
      copy: src={{FILE_PATH}}/{{JDK_VERSION}}.tar.gz dest=/opt

    - name: '创建jdk解压目录'
      shell: mkdir -p /opt/{{JDK_VERSION}}

    - name: 'jdk解压'
      shell: tar zxvf {{JDK_VERSION}}.tar.gz -C /opt/{{JDK_VERSION}}

    - name: '创建jdk软件链接'
      file: src=/opt/{{JDK_VERSION}} dest=/usr/local/java state=link

    - name: '配置/etc/profile'
      shell: /bin/echo {{ item  }} >> /etc/profile
      with_items:
        - export JAVA_HOME=/usr/local/java
        - export JRE_HOME=/usr/local/java/jre
        - export CLASSPATH=.:\$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:\$JRE_HOME/lib:\$CLASSPATH
        - export PATH=\$JAVA_HOME/bin:\$PATH

    - name: '使/etc/profile生效'
      shell: source /etc/profile

    - name: '验证jdk安装'
      shell: javac -version && java -version

