---
- hosts: aliyun
  gather_facts: false
  vars :
    FILE_PATH: /opt/files
    JDK_VERSION: jdk-8u112-linux-x64
  tasks:
    - name: '复制jdk到远程机'
      copy: src={{FILE_PATH}}/{{JDK_VERSION}}.tar.gz dest=/opt force=no

    - name: '{{JDK_VERSION}}.tar.gz解压到目录:/opt/{{JDK_VERSION}}'
      unarchive: src=/opt/{{JDK_VERSION}}.tar.gz dest=/opt/{{JDK_VERSION}} copy=no list_files=yes

    - name: '创建jdk软件链接'
      file: src=/opt/{{JDK_VERSION}} dest=/usr/local/java state=link

    - name: '配置/etc/profile'
      shell: /bin/echo {{ item  }} >> /etc/profile
      with_items:
        - export JAVA_HOME=/usr/local/java
        - export JRE_HOME=/usr/local/java/jre
        - export CLASSPATH=.:\$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:\$JRE_HOME/lib:\$CLASSPATH
        - export PATH=\$JAVA_HOME/bin:\$PATH

    - name: '使/etc/profile生效'
      shell: source /etc/profile

    - name: '验证jdk安装'
      shell: javac -version && java -version

