# Generate random password for new_user_name and the new_user_name
# is required to change his/her password on first logon.

- name: '为用户生成新密码' 
  shell: command openssl rand -base64 6
  register: user_password

- name: '为用户创建新密码' 
  shell: command openssl passwd -salt '2018model' -1 {{ user_password.stdout }}
  register: encrypted_user_password

- name: '创建新用户{{ new_user_name}},超级管理员权限'
  user:
      name: "{{ new_user_name }}"
      password: "{{ encrypted_user_password.stdout }}"
      shell: /bin/bash
      update_password: on_create
      state: present
  when: new_user_name is defined
  register: user_created

- name: '配置超级管理员' 
  lineinfile: dest=/etc/sudoers state=present  line='{{item}}' validate='visudo -cf %s'
  with_items:
     - "{{ new_user_name }} ALL=(ALL) NOPASSWD: ALL"
     - "Defaults: {{ new_user_name }}  !requiretty" 
  ignore_errors: true

- name: '修改用户密码' 
  shell: chage -d 0 {{ new_user_name }}
  when: user_created.changed

- name: '创建用户' 
  debug: msg="Password for {{ new_user_name }} is {{ user_password.stdout }}"
  when: user_created.changed
