---
- name: create dir in target server
  file: 
    path: ~/backup/gitlab
    state:  directory

- name: copy script to target server
  copy: 
    src: backupgitlab.sh
    dest: ~/backup/gitlab/backupgitlab.sh
    mode: 744

- name: install requests
  shell: pip install requests

- name: install bypy
  shell: pip install bypy    

- name: authorization
  shell: echo {{authorization_code}} | bypy info
  
- name: set cron plan
  cron: 
    name: backup gitlab project to remote-server and baiduyun
    weekday: "7"
    hour: "4"
    minute: "0" 
    job: ~/backup/gitlab/backupgitlab.sh
