---
- name: create dir in target server
  file: 
    path: /root/backupyun/gitlab
    state:  directory

- name: copy script to target server
  copy: 
    src: backupgitlab.sh
    dest: /root/backupyun/gitlab/backupgitlab.sh
    mode: 744   

- name: copy script to target server
  copy: 
    src: makedir.sh
    dest: /root/backupyun/gitlab/makedir.sh
    mode: 744 

- name: copy script to target server
  copy: 
    src: scpfile.sh
    dest: /root/backupyun/gitlab/scpfile.sh
    mode: 744 

- name: set cron plan
  cron: 
    name: backup gitlab project to remote-server and baiduyun
    hour: "3"
    minute: "0" 
    job: /root/backupyun/gitlab/backupgitlab.sh
