---
- name: create dir in target server
  file: 
    path: /root/backupyun/gitlab
    state:  directory

- name: copy script to target server
  copy: 
    src: backupgitlab.sh
    dest: /root/backupyun/gitlab/backupgitlab.sh
    mode: 744   
  
- name: set cron plan
  cron: 
    name: backup gitlab project to remote-server and baiduyun
    weekday: "7"
    hour: "4"
    minute: "0" 
    job: /root/backupyun/gitlab/backupgitlab.sh
