version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    # volumes:
      # - /storage/docker/mysql-datadir:/var/lib/mysql
