---
- name: Install pcre-devel
  apt: name={{item}} state=present
  with_items:
    - "libpcre3"
    - "libpcre3-dev"

- name: Install zlib-devel
  apt: name=zlib1g-dev state=present

- name: Install openssl-devel
  apt: name=libssl-dev state=present
  
- name: Install gcc
  apt: name=build-essential state=present  

- name: Install sysv-rc-conf
  apt: name=sysv-rc-conf state=present

- name: Install unzip
  apt: name=unzip state=present

- name: Install patch
  apt: name=patch state=present