---
- name: Create temp dir
  file:  path={{item}} state=directory
  with_items:
    - "{{ create_path }}"
    
- name: Extract Nginx
  unarchive: src={{ download_path }}/nginx-{{nginx_version}}.tar.gz dest={{download_dir}}/temp
  
- name: Extract concat mod
  include: mod_concat.yml
  when: install_mod_concat

- name: Extract gperftools
  include: mod_gperftools.yml
  when: install_mod_gperftools

- name: Extract libunwind
  include: mod_libunwind.yml
  when: install_mod_libunwind
  
- name: Extract strip
  include: mod_strip.yml
  when: install_mod_strip
  
- name: Copy Nginx Install Shell Script
  template: src=configure.sh dest={{download_dir}}/temp/nginx-{{nginx_version}} mode="u=rwx,g=rw,o=r"

- name: Configure Nginx
  command: /bin/bash /{{download_dir}}/temp/nginx-{{nginx_version}}/configure.sh

- name: Install nginx
  shell: cd {{download_dir}}/temp/nginx-{{nginx_version}}/ && make && make install
