---
- name: Extract archive
  unarchive: src={{ download_path }}/gperftools-{{gperftools_version}}.tar.gz dest={{download_dir}}/temp

- name: Install google perftools
  shell: cd {{download_dir}}/temp/gperftools-{{gperftools_version}} && ./configure --enable-frame-pointers  && make && make install




