---
# tasks file for ansible-nexus
- name: '确认nexus下载目录是否存在'
  file:
    path="{{ nexus_download_dir }}/{{ nexus_package }}"
    state="directory"

- name: '下载nexus'
  get_url: url={{ nexus_down_url }} dest="{{ nexus_download_dir }}/{{ nexus_package }}"
  tags: download

- name: '确认nexus用户组是否存在'
  group: name="{{ nexus_os_group }}" state=present
  when: nexus_create_os_group

- name: '确认nexus用户是否存在'
  user: name="{{ nexus_os_user }}" group="{{ nexus_os_group }}" shell="{{ nexus_os_user_shell }}" state=present
  when: nexus_create_os_user
  sudo: true

- name: '确认nexus安装目录是否存在'
  file:
    path="{{ nexus_installation_dir }}"
    state="directory"
  sudo: true

- name: '解压nexus目录'
  unarchive:
    src="{{ nexus_download_dir }}/{{ nexus_package }}"
    dest="{{ nexus_installation_dir }}"
    creates="{{ nexus_installation_dir }}/nexus-{{ nexus_version }}"
    force=no
    copy=false
    owner={{ nexus_os_user }}
    group={{ nexus_os_group }}
    mode="0755"
  tags: unpack

- name: '建立nexus软链接'
  shell: ln -fs `ls -d {{ nexus_installation_dir }}/nexus-*|tail -1` {{ nexus_installation_dir }}/nexus-latest

- name: '判断Nexus目录是否存在'
  stat: path="{{ nexus_installation_dir }}/sonatype-work"
  register: s_w

- name: Move existing sonatype working directory into specified working dir
  command: mv "{{ nexus_installation_dir }}/sonatype-work" "{{ nexus_working_dir }}"
  when: s_w.stat.exists

- name: Set permissions and ownership on Nexus installation directory
  file:
    path={{ nexus_installation_dir }}/{{ nexus_package }}
    state="directory"
    owner="{{ nexus_os_user }}"
    group="{{ nexus_os_group }}"
    mode="0755"
    recurse=true

- name: Set permissions and ownership on Nexus work directory
  file:
    path={{ nexus_working_dir }}
    state="directory"
    owner="{{ nexus_os_user }}"
    group="{{ nexus_os_group }}"
    mode="0755"
    recurse=true

- name: Set permissions and ownership on Nexus logs directory
  file:
    path={{ nexus_installation_dir }}/nexus-latest/logs
    owner="{{ nexus_os_user }}"
    group="{{ nexus_os_group }}"
    state=directory

- name: Set permissions and ownership on Nexus tmp directory
  file:
    path={{ nexus_installation_dir }}/nexus-latest/tmp
    owner="{{ nexus_os_user }}"
    group="{{ nexus_os_group }}"
    state=directory

- name: Set permissions and ownership on Nexus pid directory
  file:
    path=/var/run/nexus
    owner="{{ nexus_os_user }}"
    group="{{ nexus_os_group }}"
    state=directory

- name: '配置nexus端口'
  lineinfile:
    dest="{{ nexus_installation_dir }}/nexus-{{ nexus_version }}/conf/nexus.properties"
    line="application-port={{ nexus_port }}"
    regexp="application-port=.*"
    state=present
  notify:
    - 'restart nexus'

- name: Configure workdir in nexus.properties
  lineinfile:
    dest="{{ nexus_installation_dir }}/nexus-{{ nexus_version }}/conf/nexus.properties"
    line="nexus-work={{ nexus_working_dir }}"
    regexp="nexus-work=.*"
    state=present
  notify:
    - 'restart nexus'

- name: Copy the /etc/init.d/nexus file
  template: src=init-nexus.j2 dest=/etc/init.d/nexus owner=root group=root mode=0755 backup=yes
  when: ansible_os_family == "RedHat"
  notify:
    - 'restart nexus'

# - name: Register service with chkconfig system
  # service: name=nexus enabled=yes
  # when: ansible_os_family == "RedHat"

# - name: '' Set service start/stop order
  # sudo: yes
  # command: chkconfig nexus reset
  # when: ansible_os_family == "RedHat"
