---
- hosts: init-hosts
  gather_facts: false
  vars :
    group: capinfo
    user:  capinfo
    password :  capinfo
  tasks:
    - name: '安装基础软件'
      yum: name=rsync,nfs-utils,net-tools,vim,tree,htop,iftop,iotop,lrzsz,sl,wget,unzip,telnet,nmap,nc,psmisc,dos2unix,bash-completion,iotop,iftop,sysstat,screen,zip state=installed

    - name: '创建用户组{{group}}'
      group: name={{group}}

    - name: '创建用户{{user}}'
      user: name={{user}} password={{password}} create_home=yes shell=/bin/bash

    - name: '安装时间同步'
      yum: name=rsync,mailx state=installed

    - name: '将原有的hosts文件备份'
      shell: mv /etc/hosts /etc/hosts.bak

    - name: '将ansible端的hosts复制到各自机器上'
      copy: src=files/hosts dest=/etc/ owner=root group=root mode=0644

    - name: '在新的hosts文件后面追加各自机器内网ip和hostname'
      lineinfile: dest=/etc/hosts line="{{ip}}  {{hostname}}"

    - name: '配置新的hostname'
      shell : "echo {{hostname|quote}} > /etc/hostname"

    - name: '检查hostname和hosts'
      shell : "cat /etc/hostname && cat /etc/hosts"
