- hosts: all
  gather_facts: false
  vars :
    group: capinfo
    user:  capinfo
    password :  capinfo
  tasks:
    - name: install base soft
      yum: name=rsync,nfs-utils,net-tools,vim,tree,htop,iftop,iotop,lrzsz,sl,wget,unzip,telnet,nmap,nc,psmisc,dos2unix,bash-completion,iotop,iftop,sysstat,screen,zip state=installed

    - name: create group {{group}}
      group: name={{group}}

    - name: create user {{user}}
      user: name={{user}} password={{password}} create_home=yes shell=/bin/bash

    - name: install rsync server
      yum: name=rsync,mailx state=installed

    - name: change name
       raw: "echo {{hostname|quote}} > /etc/hostname"
     - name:
       shell: hostname {{hostname|quote}}

