---
- name: '从{{java_download_url}}下载{{java_tar_file}}'
  get_url:
    url: "{{ java_download_url }}"
    dest: "{{ java_tar_file }}"
  when: java_download_from_oracle

- name: '确认安装目录{{ java_install_dir }}是否存在'
  file:
    path: "{{ java_install_dir }}"
    mode: 0755
    owner: root
    group: root
    state: directory

- name: '查看{{ java_real_home }}是否存在'
  stat: path="{{ java_real_home }}"
  register: java_real_home_check

- name: '解压{{ java_tar_file }}到{{ java_install_dir }}目录'
  unarchive:
    src: "{{ java_tar_file }}"
    dest: "{{ java_install_dir }}"
    owner: root
    group: root
    copy: no
  when: java_real_home_check.stat.isdir is not defined or not java_real_home_check.stat.isdir

- name: '确认Java默认配置清理'
  file: path="/var/lib/alternatives/{{ item }}" state=absent
  with_items:
    - java
    - keytool
    - javac
    - javadoc
    - jar

- name: '设置可选链接'
  alternatives:
    name="{{ item.exe }}"
    link="/usr/bin/{{ item.exe }}"
    path="{{ item.path }}/{{ item.exe }}"
  with_items:
    - { path: "{{ java_real_home }}/jre/bin", exe: 'java' }
    - { path: "{{ java_real_home }}/jre/bin", exe: 'keytool' }
    - { path: "{{ java_real_home }}/bin", exe: 'javac' }
    - { path: "{{ java_real_home }}/bin", exe: 'javadoc' }
    - { path: "{{ java_real_home }}/bin", exe: 'jar' }

- name: '确认默认Java链接被清理'
  file: path="/usr/java/default" state=absent

- name: '确认Java链接被清理'
  file: path="/usr/java/latest" state=absent

- name: '配置Java /dev/urandom'
  lineinfile:
    dest="{{ java_real_home }}/jre/lib/security/java.security"
    regexp="^securerandom.source="
    line="securerandom.source=file:/dev/./urandom"
  when: java_entropy_fix

- name: '清理临时文件'
  file:
    path: "{{ java_download_path }}/{{ item }}"
    state: absent
  with_items:
    - "jdk-{{ java_version }}-linux-x64.tar.gz"
  when: java_remove_download
