- name: yum 卸载 ntp
  shell: 'yum remove -y ntp'
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'
  args:
      warn: false
  ignore_errors: true

- name: 安装 chrony
  package: name=chrony state=present

- name: 配置 chrony server
  template: src=server-centos.conf.j2 dest=/etc/chrony.conf
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'

- name: 启动 chrony server
  service: name=chronyd state=restarted enabled=yes
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'

- name: 配置 chrony client
  template: src=client-centos.conf.j2 dest=/etc/chrony.conf
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'

- name: 启动 chrony client
  service: name=chronyd state=restarted enabled=yes
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'
