---
- hosts: 127.0.0.1
  gather_facts: no
  become: false
  become_user: root
  become_method: su
  vars :
    group: capinfo
    user:  capinfo
    password :  capinfo
  tasks:
    - name: '初始化[ANSIBLE-INVENTORY]文件'
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
        - { src: 'files/hosts', dest: '~/.ansible/hosts' }
