---
- name: '服务器监控检查'
  hosts: all
  gather_facts: no
  tasks:
    - name: '检查服务器是否正常连通'
      ping:

    - name: '监控操作系统CPU和磁盘使用情况 ...'
      shell: |
        free -m | awk 'NR==2{printf "内存使用: %s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }'
        df -h | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{ print "硬盘使用:"" " $1 " " $3"/"$2" ""("$5")"}'
        netstat -an | awk '/^tcp/ {a[$NF]++} END {for (b in a) print b,a[b]}' | awk '{ print "TCP连接:"" " $1 " " $2""}'
        jps -l | awk '{print "Java应用:" $2 " 进程 " $1}'
      register: out
    - debug: var=out.stdout_lines

- name: '基础平台服务健康检查'
  hosts: 172.20.200.78
  gather_facts: no
  tasks:
    - name: '应用健康检查'
      wait_for:
        host: "{{ item.ip }}"
        port: "{{ item.port }}"
        state: started         # Port should be open
        delay: 0               # No wait before first check (sec)
        timeout: 3             # Stop checking after timeout (sec)
      ignore_errors: yes
      with_items:
        - { ip : '172.20.200.76', port : '7001', desc : "【开发】广州公积金云桌面" }
        - { ip : '172.20.200.76', port : '8001', desc : "【测试】广州公积金云桌面" }
        - { ip : '172.20.200.79', port : '9000', desc : "【平台】SVN代码托管" }
        - { ip : '172.20.200.79', port : '80', desc : "【平台】GITLAB代码托管" }
        - { ip : '172.20.200.76', port : '8090', desc : "【平台】Confluence企业文档" }
        - { ip : '172.20.200.77', port : '8080', desc : "【平台】分布式配置中心" }
        - { ip : '172.20.200.76', port : '81', desc : "【平台】禅道" }
        - { ip : '172.20.200.81', port : '9000', desc : "【平台】分布式云存储" }
        - { ip : '60.247.77.123', port : '8888', desc : "【平台】电子签名_签章服务器" }
        - { ip : '60.247.77.125', port : '28002', desc : "【平台】电子签名_信手书服务器" }

        - { ip : '172.20.200.77', port : '18000', desc : "【开发】广州Dubbo控制台" }
        - { ip : '172.20.200.75', port : '18000', desc : "【开发】百色Dubbo控制台" }
        - { ip : '172.20.200.80', port : '8080', desc : "【开发】普元工作流控制台" }
        - { ip : '172.20.200.80', port : '8885', desc : "【开发】迈安控制台" }
        - { ip : '172.20.200.80', port : '8089', desc : "【开发】微模式控件" }
        - { ip : '172.20.200.77', port : '6379', desc : "【开发】Redis监控" }
        - { ip : '172.20.200.77', port : '2181', desc : "【开发】Zookeeper监控" }
        - { ip : '272.20.200.80', port : '8089', desc : "【开发】Kafka监控" }

        - { ip : '172.20.200.82', port : '18000', desc : "【测试】广州Dubbo控制台" }
        - { ip : '172.20.200.75', port : '18001', desc : "【测试】百色Dubbo控制台" }
        - { ip : '172.20.200.83', port : '8080', desc : "【测试】普元工作流控制台" }
        - { ip : '172.20.200.83', port : '8885', desc : "【测试】迈安控制台" }
        - { ip : '172.20.200.83', port : '8089', desc : "【测试】微模式控件" }
        - { ip : '172.20.200.82', port : '6379', desc : "【测试】Redis监控" }
        - { ip : '172.20.200.82', port : '2181', desc : "【测试】Zookeeper监控" }
        - { ip : '172.20.200.82', port : '9000', desc : "【测试】Kafka监控" }

        - { ip : '172.20.200.77', port : '8081', desc : "【广州】私服" }
        - { ip : '172.20.200.82', port : '8081', desc : "【广州】私服" }
        - { ip : '272.20.200.83', port : '8081', desc : "【南宁】私服" }
        - { ip : '272.20.200.83', port : '8081', desc : "【南宁】私服" }
        - { ip : '172.20.200.75', port : '8081', desc : "【百色】私服" }
        - { ip : '172.20.200.75', port : '8082', desc : "【百色】私服" }

        - { ip : '172.20.200.79', port : '3306', desc : "【开发】MySQL数据库" }
        - { ip : '172.20.200.7', port : '1521', desc : "【开发】Oracle数据库" }
        - { ip : '172.20.200.8', port : '1521', desc : "【测试】Oracle数据库" }















