---
# file: tasks/install-prometheus.yml
# Install Prometheus server.
# @see http://prometheus.io/docs/introduction/getting_started/

- name: set internal variables for convenience
  set_fact:
    prometheus_tarball_url: "{{ prometheus_download_url }}/prometheus-{{ prometheus_version }}.{{ prometheus_platform_suffix }}.tar.gz"
    prometheus_daemon_dir: "{{ prometheus_install_path }}/prometheus-{{ prometheus_version }}.{{ prometheus_platform_suffix }}"
- name: download and untar prometheus tarball
  unarchive:
    src: "{{ prometheus_tarball_url }}"
    dest: "{{ prometheus_install_path }}"
    copy: no

- name: set permissions, owner and group
  file:
    path: "{{ prometheus_install_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "go-w"
    recurse: yes

- name: mkdir for config and data
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ prometheus_rule_path }}"
    - "{{ prometheus_file_sd_config_path }}"
    - "{{ prometheus_db_path }}"

- name: set prometheus variables
  copy: src="../files/etc-default-prometheus"  dest=/etc/default/prometheus

- name: copy INIT script to server
  template: src="../templates/prometheus.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/prometheus"  mode="a+x"
  when: not prometheus_use_systemd|bool

- name: copy systemd config to server
  template: src="../templates/prometheus.service.j2"  dest="/etc/systemd/system/prometheus.service"
  when: prometheus_use_systemd|bool

- name: set INIT status
  service: name=prometheus enabled=yes
  when: prometheus_use_service|bool

- name: copy rule files from playbook's, if any
  copy:
    src: "{{ playbook_dir }}/{{ item.value.src }}"
    dest: "{{ prometheus_rule_path }}/{{ item.value.dest }}"
    validate: "{{ prometheus_daemon_dir }}/promtool check rules %s"
  with_dict: '{{ prometheus_rule_files | default({}) }}'
  notify:
    - reload prometheus

- name: copy prometheus main config file from role's default, if necessary
  template:
    src: "../templates/prometheus.yml.j2"
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    validate: "{{ prometheus_daemon_dir }}/promtool check config %s"
  when: prometheus_conf_main is not defined
  notify:
    - reload prometheus

- name: copy prometheus main config file from playbook's, if any
  template:
    src: "{{ playbook_dir }}/{{ prometheus_conf_main }}"
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    validate: "{{ prometheus_daemon_dir }}/promtool check config %s"
  when: prometheus_conf_main is defined
  notify:
    - reload prometheus

