---
- name: '安装Open-JDK 1.8'
  yum: name=java-1.8.0-openjdk state=present

- name: '添加tomcat分组'
  group: name=tomcat

- name: '创建{{ tomcat_home }}目录'
  file:
    path: "{{ tomcat_home }}"
    state: directory
  become_method: sudo

- name: '添加tomcat用户'
  user: name=tomcat group=tomcat home={{ tomcat_home }} createhome=no
  become: True
  become_method: sudo

- name: '下载Tomcat8.5.51'
  get_url: url={{tomcat_down_url}} dest={{ tomcat_home }}/{{ tomcat_name }}.tar.gz

- name: '解压Tomcat'
  command: chdir={{ tomcat_home }} /bin/tar xvf {{ tomcat_home }}/{{ tomcat_name }}.tar.gz -C {{ tomcat_home }} creates={{ tomcat_home }}/{{ tomcat_name }}

- name: '切换Tomcat用户操作'
  file: path={{ tomcat_home }} owner=tomcat group=tomcat state=directory recurse=yes

- name: '配置Tomcat'
  template: src=server.xml dest={{ tomcat_home }}/{{ tomcat_name }}/conf
  notify: restart tomcat

- name: '配置Tomcat 用户'
  template: src=tomcat-users.xml dest={{ tomcat_home }}/{{ tomcat_name }}/conf
  notify: restart tomcat

- name: '安装Tomcat启动脚本'
  copy: src=tomcat-initscript.sh dest={{ tomcat_home }}/{{ tomcat_name }} mode=0755

- name: '部署Tomcat防火墙'
  template: src=iptables-save dest=/etc/sysconfig/iptables
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"
  notify: restart iptables

- name: '启动Tomcat'
  shell: sh {{ tomcat_home }}/{{ tomcat_name }}/tomcat-initscript.sh

  #- name: 'Tomcat启动中...'
  # wait_for: port={{http_port}}
