---
- hosts: mysql
  gather_facts: false
  become: yes
  become_user: root
  become_method: su
  tasks:
    - name: '安装MariaDB包'
      package:
        name: "{{ item }}"
        state: installed
      with_items:
        - MariaDB-common
        - MariaDB-server
        - MySQL-python
      tags: mariadb

    - name: '安装服务器配置'
      template:
        src: etc_my.cnf.d_server.cnf.j2
        dest: "{{ mariadb_config_server }}"
      notify: restart mariadb
      tags: mariadb

    - name: '配置网络'
      template:
        src: etc_my.cnf.d_network.cnf.j2
        dest: "{{ mariadb_config_network }}"
      notify: restart mariadb
      tags: mariadb

    - name: '安装客户端配置'
      template:
        src: etc_my.cnf.d_custom.cnf.j2
        dest: "{{ mariadb_config_custom }}"
      when: mariadb_custom_cnf|length != 0
      notify: restart mariadb
      tags: mariadb

    - name: '配置swappiness'
      sysctl:
        name: vm.swappiness
        value: "{{ mariadb_swappiness }}"
        state: present
      when: mariadb_configure_swappiness|bool
      tags: mariadb

    - name: '确保mariadb已经启动'
      service:
        name: "{{ mariadb_service }}"
        state: started
        enabled: true
      tags: mariadb
