---
- hosts: all
  gather_facts: false
  become: yes
  become_user: root
  become_method: su
  vars :
    FILE_PATH: /opt
    JDK8_VERSION: jdk-8u112-linux-x64
    JDK7_VERSION: jdk-7u79-linux-x64
  tasks:
    - name: '复制{{JDK8_VERSION}}到远程机'
      copy: src={{FILE_PATH}}/{{JDK8_VERSION}}.tar.gz dest=/opt force=no

    - name: '创建/opt/{{JDK8_VERSION}}目录'
      file: path=/opt/{{JDK8_VERSION}} state=directory

    - name: '{{JDK8_VERSION}}.tar.gz解压到目录:/opt/{{JDK8_VERSION}}'
      unarchive: src=/opt/{{JDK8_VERSION}}.tar.gz dest=/opt/{{JDK8_VERSION}} copy=no list_files=yes

    - name: '复制{{JDK7_VERSION}}到远程机'
      copy: src={{FILE_PATH}}/{{JDK7_VERSION}}.tar.gz dest=/opt force=no

    - name: '创建/opt/{{JDK7_VERSION}}目录'
      file: path=/opt/{{JDK7_VERSION}} state=directory

    - name: '{{JDK7_VERSION}}.tar.gz解压到目录:/opt/{{JDK8_VERSION}}'
      unarchive: src=/opt/{{JDK7_VERSION}}.tar.gz dest=/opt/{{JDK7_VERSION}} copy=no list_files=yes

    - name: '使/etc/profile生效'
      shell: source /etc/profile

    - name: '验证jdk安装'
      shell: javac -version && java -version

