---
- hosts: 47.92.68.183
  vars:
    NFS_UPLOAD_PATH: /upload
  tasks:
  - name: '安装最新的同步工具达到最新版本'
    yum:
      name: nfs-utils,rpcbind
      state: latest
  
  - name: '运行rpcbind'
    service:
      name: rpcbind
      state: started
      enabled: yes
      
  - name: '运行nfs'
    service:
      name: nfs
      state: stoped
      enabled: no
      
  - name: '创建{{NFS_UPLOAD_PATH}}目录 '
    file:
      path: "{{NFS_UPLOAD_PATH}}"
      state: directory
      
  - name: '挂载{{NFS_UPLOAD_PATH}}目录 '
    mount:
    path: /mnt/dvd
    src: /dev/sr0
    fstype: iso9660
    opts: ro,noauto
    state: present