---
# variables needed to be defined in user's playbook
# user-configurable defaults
# prometheus_node_exporter_version:   0.16.0

prometheus_user:   prometheus
prometheus_group:  prometheus

prometheus_version:                 2.17.1
prometheus_alertmanager_version:    0.20.0

gosu_version: "1.11"
prometheus_go_version:   1.11

prometheus_install_path:         /opt/prometheus
prometheus_config_path:          /etc/prometheus
prometheus_rule_path:            "{{ prometheus_config_path }}/rules"
prometheus_file_sd_config_path:  "{{ prometheus_config_path }}/tgroups"
prometheus_db_path:              /var/lib/prometheus
prometheus_log_path:             /var/log/prometheus
prometheus_pid_path:             /var/run/prometheus
prometheus_alertmanager_db_path: /var/lib/alertmanager

prometheus_download_path: /tmp
prometheus_workdir:       "{{ prometheus_download_path }}/prometheus_workdir"
prometheus_goroot:        "{{ prometheus_workdir }}/go"
prometheus_gopath:        "{{ prometheus_workdir }}/gopath"

prometheus_clean_tarball:     true

# rebuild each time?  (only applied to `git` version)
prometheus_rebuild:           false

# email config
alertmanager_smtp_from:       "linesno_cloud@163.com"
alertmanager_smtp_host:       "smtp.163.com:25"
alertmanager_smtp_username:       "linesno_cloud@163.com"
alertmanager_smtp_password:       "1234qwer"

# prometheus monitor define
# prometheus_mysql_monitor:     "47.113.116.150:19888"
# consul_sd_host:               "47.111.108.91:8500"
# prometheus_jenkins_monitor:   "jenkins.lbxinhu.com"

# derived variables; internal use only.
#---- the following vars are handled in tasks/set-role-variables.yml ------

#prometheus_use_systemd: False  # use "systemd" to start/restart service?
