- name: "判断进程是否存在"
  hosts: all
  connection: all
  user: root
  gather_facts: false
  ignore_errors: yes

  - name: Check if nginx is running
    command: systemctl status nginx
    ignore_errors: yes
    changed_when: false
    register: service_nginx_status

  - name: Report status of nginx
    fail:
     msg: |
        Service nginx is not running.
        Output of `systemctl status nginx`:
        {{ service_nginx_status.stdout }}
        {{ service_nginx_status.stderr }}
    when: service_nginx_status is failed

  - name: Look for the "{{ item.name }}" process
    shell: ps -ef | grep {{ item.name }}| grep -v grep
    register: process_list
    changed_when: false
    with_items:
       - { name : "jenkins"}

  - name: 启动"jenkins"服务
    shell: jenkins服务没有在运行
    when: "process_list.stdout.find('jenkins') == -1"

  - name: 启动"nexus"服务
    shell: nexus服务没有在运行
    when: "process_list.stdout.find('nexus') == -1"

